### ISSUE TITLE
String type property values with leading numbers aren't wrapped in double quotes when exported to Cypher

### ISSUE THREAD

**Issue by mattmodarres** [neo4j-labs/arrows.app#1]
This results in an invalid query.

The issue applies to both node and relationship properties. Numbers elsewhere in the string are handled correctly.

For example:
A `Location` node with property `address: 123 Main Street` will result in `(n2:Location {address: 123 Main Street})` when exported to Cypher, whereas using `address: Main Street` will give `(n2:Location {address: "Main Street"})`.

Tested in Firefox and Chrome.

**Comment by apcj** [comment]
Thanks @mattmodarres . This definitely a bug - will fix it soon.

**Comment by apcj** [comment]
Now fixed. Please make sure you hard refresh to get the latest code.
