### ISSUE TITLE
Blank screen when loading

### ISSUE THREAD

**Issue by ryancasburn-KAI** [neo4j-labs/arrows.app#111]
https://arrows.app/ is completely blank on load.  There is an uncaught error in the console:

Uncaught Error: Minified Redux error #0; visit https://redux.js.org/Errors?code=0 for the full message or use the non-minified dev environment for full errors. 
    at qO (index-2343261e.js:75:3010)
    at index-2343261e.js:185:37909
    at index-2343261e.js:1:23
    at index-2343261e.js:185:38246

**Comment by ryancasburn-KAI** [comment]
Seems to be working now

**Comment by CraigDeverall** [comment]
I have this again now.

index-2343261e.js:75 Uncaught Error: Minified Redux error #0; visit https://redux.js.org/Errors?code=0 for the full message or use the non-minified dev environment for full errors. 
    at qO (index-2343261e.js:75:3010)
    at index-2343261e.js:185:37909
    at index-2343261e.js:1:23
    at index-2343261e.js:185:38246Understand this error
cc.js?renew=false&referer=arrows-app-295615.nw.r.appspot.com&dnt=false&init=false:1 Error: The domain ARROWS-APP-295615.NW.R.APPSPOT.COM is not authorized to show the cookie banner for domain group ID 0c2ea320-7217-4e6b-91f2-77765fc83255. Please add it to the domain group in the Cookiebot Manager to authorize the domain.
