### ISSUE TITLE
Zoom on graph only

### ISSUE THREAD

**Issue by viktorht** [neo4j-labs/arrows.app#16]
Hi!

Thank you for developing this nice program!

Is it possible to zoom in the canvas? Currently, I can only use the zoom function in my browser but this makes the side panel become very small when zooming out.

Here is a picture of what I mean
<img width="868" alt="image" src="https://user-images.githubusercontent.com/60354512/106598730-6e7ac880-6558-11eb-9d44-8c52438de2c6.png">

I'm using Firefox.

Best
Viktor

**Comment by apcj** [comment]
Hi @viktorht , yes you should be able to zoom, if you have a mouse or trackpad. Try holding down control and scrolling with your mouse. If you have a Mac you also use the pinch gesture on the trackpad.

Let me know if that works for you. We'll consider adding some help for this.

**Comment by apcj** [comment]
Hi @viktorht going to close this issue for now. Please comment or re-open if this is still a problem for you.
