### ISSUE TITLE
JSON Import 

### ISSUE THREAD

**Issue by willneumann** [neo4j-labs/arrows.app#17]
Is there a way to import a graph to the arrows.app?

My use case is as follows: Once I've drawn up a graph in the arrows.app, I'd like to share it with other people so they can keep working on it in arrows.app.

Here's the flow:
1. I create a graph in arrows.app
2. I export the graph in JSON format
3. Send it to another person
4. The person imports the graph into their own browser session on arrows.app

Is 4. above doable?

**Comment by apcj** [comment]
Hi @willneumann I think what you are asking about it possible, but possibly I don't completely understand what you're asking for. Have a look at the Import item on the main dropdown menu:

![image](https://user-images.githubusercontent.com/98962/109431181-19b65a80-79fd-11eb-9e58-0f6cec1c4370.png)

Possibly, you haven't even seen this menu? It needs to become more obvious if so.

**Comment by cadserf** [comment]
One issue I have found there is that the theme is derived from the existing "canvas" rather than from the imported json.

**Comment by willneumann** [comment]
Hi @apcj, right. I didn't see that menu at all, if you could make it more obvious to people, that would be fantastic. That answers my question, thanks a bunch!

**Comment by apcj** [comment]
@willneumann glad that you found the menu! I will look into how to make it more obvious.

I'm going to close this specific issue, because JSON import _is_ available.

@cadserf your comment sounds like a limitation of the JSON import feature. I will start a conversation about that on the other issue you raised.
