### ISSUE TITLE
Defaults sizes as settings

### ISSUE THREAD

**Issue by wadael** [neo4j-labs/arrows.app#19]
Tool is not user-friendly on a tiny detail. (I appreciate the tool and its public availability. Will shake hands and offer sthg asap next time in London)

I'd like not to have to change all sizes for all properties of each node

I presume you guys have 4K displays as 40 is too large on 1080p.

**Comment by apcj** [comment]
Hi @wadael thanks for the appreciation! About default sizes, I think this is already supported - just change the sizes when you have nothing selected and it will apply to all nodes. It works something like CSS - when nothing is selected you are choosing style for the whole graph, which can then be overridden for specific nodes or relationships.
