### ISSUE TITLE
Export using Run in Neo4j Browser

### ISSUE THREAD

**Issue by jim-kywslp** [neo4j-labs/arrows.app#21]
Must have missed something but , When I try to export to Neo4j Browser I can't get it to work.
I have Neo4j Desktop and Neo4j Browser running but not seeing anything in browser when arrows exports.

**Comment by apcj** [comment]
Hi @jim-kywslp that's funny - it should populate the cypher editor in Neo4j Browser via a `neo4j-desktop:` protocol handler.

Can I ask what web browser and operating system you are using? Also, please can you check whether the similar buttons in the Neo4j documentation work for you? For example, see the "Run in Neo4j Browser" button on this page: https://neo4j.com/docs/cypher-manual/current/clauses/optional-match/#query-optional-match

**Comment by apcj** [comment]
@jim-kywslp I'm going to close this issue for now. Please re-open or write a comment if this is still a problem for you. thanks!
