### ISSUE TITLE
Bug: use as labels/properties doesn't work

### ISSUE THREAD

**Issue by versusnja** [neo4j-labs/arrows.app#28]
![image](https://user-images.githubusercontent.com/1716025/117294360-dbad3b00-ae72-11eb-8212-b00db3a6b8f1.png)

When any of two buttons is clicked, nothing happens. There are no errors in the console too.
Latest Safari on Mac.

**Comment by versusnja** [comment]
This was when I had nodes, but had no relationships. When I created relationships, I could see the names in Cypher.
Without relationships the nodes in Cypher where without a name

**Comment by apcj** [comment]
Hi @versusnja thanks for spotting this! This seems to be a problem in (at least) Safari on Mac. In case it helps until we fix this, the same feature does work in Chrome.

**Comment by versusnja** [comment]
@apcj Arrows.app currently isn't loading in Safari at all.
404 error on a JS script
![image](https://user-images.githubusercontent.com/1716025/118639509-45fd9e00-b7d8-11eb-9b47-846f200c2ba3.png)

**Comment by versusnja** [comment]
flushed cache fixed the problem

**Comment by apcj** [comment]
Hi @versusnja we worked around this by only opening the popup on a click event, instead of focus. Would you be able to check whether this has fixed the problem for you in Safari? (we think it will fix it for you) Thanks in advance.

**Comment by apcj** [comment]
Hi @versusnja, we changed the behaviour here to require a click, rather than just focus. This fixes the problem in Safari. Please let us know if you get a chance to try this out.
