### ISSUE TITLE
Labels as drop-down would be great

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/arrows.app#3]
Existing labels as a editable drop-down would be nice or one of those comma separated tag-lists

**Comment by apcj** [comment]
Thanks @jexp. I have something in mind that will help with this. Will revisit this issue when that solution is in place.

**Comment by apcj** [comment]
This was added a few weeks ago:
![image](https://user-images.githubusercontent.com/98962/113415529-50dea980-93b7-11eb-8b43-a806d256ed1f.png)

Also does something similar for properties keys, and property values.

**Comment by jexp** [comment]
Cool 😎 thanks a lot
