### ISSUE TITLE
Arrows blanks out, loses top control bar, Rt. Control panel, bottom banner AND graph. White out with no controls.

### ISSUE THREAD

**Issue by CommanderChipset** [neo4j-labs/arrows.app#30]
Arrows intermittently blanks out, losing its top control bar and side control panel, and bottom banner, AND graph when firefox restores its tab. I.e. when an arrows graph is on a tab when firefox closes. When firefox opens again that tab will sometimes be completely blank (wish I could show you.) There are no controls to click on, no way to restore anything. Once this happens it's gone.
--I'm storing the graph on the browser local storage and backing up to .json files (would have lost weeks if I hadn't.) The only "solution" I've found is to delete the arrows cookie data and then go to arrrows.app like it's the first time. Brand new, the controls are back and there's no graph but I can import from .json files.
--But it happened again because, I think, I left the graph on the tab because I forgot and -zing!- gone again. Anybody else have this problem?

**Comment by apcj** [comment]
Hi @CommanderChipset sorry to hear about the problems you are having. Do you have any exceptions in the Javascript console that might help diagnosis?

**Comment by apcj** [comment]
I'm going to close this for now, but please re-open if you are still having this problem.
