### ISSUE TITLE
open source

### ISSUE THREAD

**Issue by hpl002** [neo4j-labs/arrows.app#31]
Why not make this a open source project so that we can actually fix issues and add improvements.

neo4j can be the project owner and steer the overall direction.

A primary concern for me being that this app will be deprecated and therefore unavailable.

Would be nice go get thoughts on this..

Thanks, Herman

**Comment by apcj** [comment]
Hi @hpl002 thanks for your interest. I'm afraid there are not yet any firm plans about the long-term future of this app. For now, the best we can offer is this statement from [Neo4j Labs](https://neo4j.com/labs/):

> A project typically either graduates to being maintained as a formal Neo4j project or is deprecated with source made available publicly.

We'll be sure to make the direction clear as soon as we've made a decision.
