### ISSUE TITLE
Lost my diagram

### ISSUE THREAD

**Issue by scassells** [neo4j-labs/arrows.app#38]
After working for 2 hours, my diagram disappeared.

**Comment by apcj** [comment]
Hi @scassells sorry to hear that. Were you using Local Storage or Google Drive? Did you happen to look in the Javascript console for any error messages there?

**Comment by deeenes** [comment]
Something similar happened to me using local storage: it's enough to click on the top left arrow icon or navigate somewhere else and the diagram is gone. Checking the browser local storage I can find the JSON. Choosing "Local storage" from the opening panel creates an empty diagram. Eventually the diagram returned twice, not clear how it happened, I reloaded the page and went back in browser history. But I think if an empty diagram opens, once you modify it, it overwrites the data in local storage and then your previous work is really gone.

The solution could be to store each diagram under its own key in the local storage JSON, and add a menu to the app where the list of saved diagrams is available, and the user can open, duplicate or delete any of them.

**Comment by apcj** [comment]
Closing this issue for now.

**Comment by omasoud** [comment]
It would be nice to utilize Google Drive version history capabilities (like doc and sheets).
