### ISSUE TITLE
Import of Arrow graph

### ISSUE THREAD

**Issue by stasha-g** [neo4j-labs/arrows.app#39]
Hi, I can't find the feature to import a graph I drew with the previous Arrows app. 
I could load my graph in the old version by clicking 'Export Graph' and changing and saving it there to load it. 
Other than that, great improvements. I like the centering of nodes with circle a lot. Would be cool to have few other planes. 
Thank you! I am very glad to see this, as I always liked the tool a lot!

**Comment by apcj** [comment]
Hi @stasha-g thanks for the feedback. About snapping, please try refreshing now - snapping just got a bit upgrade, today.

About importing from [classic arrows](https://www.apcjones.com/arrows/), are you using the "Try Arrows.app" button?

![image](https://user-images.githubusercontent.com/98962/133930989-dd35d315-79d7-4614-a4cc-6680b9ad1cc2.png)

Right now that is the only way to transfer from one to the other but it would be possible to build a parser for the old format if it's needed.
