### ISSUE TITLE
It would be nice to have a delete button for nodes and relationships

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/arrows.app#4]
Similar to the "duplicate" button, as sometimes deletion via keyboard doesnt work.

**Comment by apcj** [comment]
Fair. Will add a delete button.

**Comment by cope** [comment]
Is this button available?
I'm not finding it in https://arrows.app/

It feels a bit scary to add a node/relationship knowing I have no way to delete it...

**Comment by apcj** [comment]
Hi @cope sorry for missing your comment. It is possible to delete things - you just have to use the keyboard to do it. Press Delete or Backspace.

**Comment by apcj** [comment]
Added a Delete button. It looks like this:

![image](https://user-images.githubusercontent.com/98962/149675162-5a9b4e4c-ca7e-469f-addd-a3f7f28433b4.png)

Thanks @jexp and @cope for the feedback about lacking this button.
