### ISSUE TITLE
Google Drive authorization: redirect_uri_mismatch

### ISSUE THREAD

**Issue by deeenes** [neo4j-labs/arrows.app#41]
Choosing the Google Drive -> New diagram from the opening menu, a browser window pops up with an error message from google: 

> Authorization Error
> Error 400: redirect_uri_mismatch
> 
> You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.
> 
> If you're the app developer, register the JavaScript origin in the Google Cloud Console.
>
> 
> If you’re the app developer, make sure that these request details comply with Google policies.
> 
>     origin: https://neo4j-arrows.appspot.com

The message also advises to look for explanation on this page: https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow#authorization-errors-origin-mismatch

**Comment by apcj** [comment]
This definitely looks to be caused by using the old domain. Sorry for the inconvenience.
