### ISSUE TITLE
Old version deployed at another domain?

### ISSUE THREAD

**Issue by deeenes** [neo4j-labs/arrows.app#42]
I've just found that the app is publicly available at two domains: https://neo4j-arrows.appspot.com and https://arrows.app. The first one is either an old version, or bad deployment, but key functionalities don't work. I think this is the reason behind issues #38, #40 and #41. The arrows.app domain works just fine. I think would be best to shut down the first domain or redirect it to the second one, otherwise people will keep finding it and experiencing issues.

**Comment by apcj** [comment]
Thanks for reporting this @deeenes. I had forgotten about the old domain! I have simply disabled the old domain for now - serving HTTP 404. I will look into adding a redirect if people complain.
