### ISSUE TITLE
Interactive maintenance of a large graph

### ISSUE THREAD

**Issue by saliez** [neo4j-labs/arrows.app#44]
How to navigate in a large graph with possibility to create or update some relationships and nodes? in an interactive visual way like arrows.app ?
More at 
http://www.chos-wg.org/Temp/WEB-GRAPH-AI/Human-Machine-Interface/Requirements-Human-interface.html

**Comment by apcj** [comment]
Hi @saliez If you are looking for a way to explore a large graph I recommend [Neo4j Bloom](https://neo4j.com/product/bloom/).
