### ISSUE TITLE
BUG: Cannot save diagram to shared drive, FIX: add supportsAllDrives parameter to GET, PATCH calls

### ISSUE THREAD

**Issue by pavelsevcik** [neo4j-labs/arrows.app#46]
## BUG: Cannot save diagram to shared drive

currently arrows.app > open > google drive can browse diagrams in shared drives

![Selection_1561](https://user-images.githubusercontent.com/5997075/142746092-745da400-53d6-4bc2-aef9-21bc7a33a257.png)

it also loads diagram content, but it fails to load diagram name and save updates to diagram in shared drive

![image](https://user-images.githubusercontent.com/5997075/142746167-40c9fd7d-5850-4fe9-98df-cb0fcd95ef6e.png)

network shows, that GET and PATCH fails, while GET for ?alt=media passes

![Selection_1563](https://user-images.githubusercontent.com/5997075/142746414-d6fbb538-0a07-4523-986e-1f9f086dd49e.png)
![Selection_1566](https://user-images.githubusercontent.com/5997075/142746415-68854c28-eabb-4c5a-8e48-0813f76e388a.png)
![Selection_1567](https://user-images.githubusercontent.com/5997075/142746416-da725cd2-4753-4b5a-a1fa-29db23d590ba.png)

## FIX: add supportsAllDrives parameter to GET, PATCH calls

- https://developers.google.com/drive/api/v3/reference/files/get
- https://developers.google.com/drive/api/v3/reference/files/update

![image](https://user-images.githubusercontent.com/5997075/142747552-1cfff43f-682e-4da9-b0a6-4ef7cd85365b.png)

![Selection_1569](https://user-images.githubusercontent.com/5997075/142747647-4adbbe87-d00d-46f3-b4bc-dbee96e79dc5.png)

![Selection_1568](https://user-images.githubusercontent.com/5997075/142747601-036e9933-5763-42e9-999f-c9f251dfdea3.png)

**Comment by anafvidal** [comment]
I had a similar issue. I manually saved the file in the shared drive (I first saved it in my personal drive). And then I could not install the arrows plugin to be able to open the file in arrows from the shared drive.

**Comment by apcj** [comment]
Hi @pavelsevcik thanks for reporting this, and especially for your thorough investigation. Also thanks for @anafvidal for reporting too.

I have added the `supportsAllDrives=true` parameter as you suggest. I seem to be able to edit files in a team drive. Please let me know if this doesn't work for you and I'll have another look.

Reminder: please make sure you hard-refresh to ensure you have the latest code.
