### ISSUE TITLE
save-as option

### ISSUE THREAD

**Issue by jjansenvr** [neo4j-labs/arrows.app#49]
I am trying to split up a drawing so i would like to save-as so i can save under another name.

**Comment by apcj** [comment]
Hi @jjansenvr I agree that this would be a very useful feature. I'll have a go at implementing it soon.

**Comment by apcj** [comment]
Hi again @jjansenvr this is now implemented. Looks like this:

![image](https://user-images.githubusercontent.com/98962/151719848-61bf7aa9-1a9f-4149-a1d6-280049ad72c6.png)

I hope this works for you? Just make sure that you hard-reload the page to get the latest code.

**Comment by jjansenvr** [comment]
I have tested it and it works like a charm! this will improve the usability for me and others. 

Thanks a lot for acting so promptly, 
If you like i can keep sending feedback in the form of issues for yu to improve the user experience.

I see your project code is not available on github, is it open source? 

I work on the functional part of https://github.com/ibissource/frank-flow graphical interface on our opensource integration framework. now using your tool for a graph implementation for a customer.

jeroen
