### ISSUE TITLE
Pressing "Return" in one of the sidebar form fields duplicates the node (with rels)

### ISSUE THREAD

**Issue by jexp** [neo4j-labs/arrows.app#5]
I had this several times where I added a label or changed a font-size and hit <Return> in the side-bar text-field which caused the node and it's relationships to be duplicated.

Nothing in the JS console.

**Comment by apcj** [comment]
I believe this happens because Enter is submitting a form, and the "duplicate" button gets activated as a side effect. I probably need a generic event handler to `preventDefault()` in all the right places.

**Comment by apcj** [comment]
Now fixed.
