### ISSUE TITLE
How do I use saved Cypher code to reinstate my arrow mockup? 

### ISSUE THREAD

**Issue by olmansju** [neo4j-labs/arrows.app#53]
Hi, I have some graphs I've been working on. I'd like to switch between them as I work but I don't know how to re-import the cypher code I have saved. Could you please tell me how I can do that? Thanks! -Justin

**Comment by apcj** [comment]
Hi @olmansju there is unfortunately no way to import cypher at the moment. However, it's quite easy to work on multiple diagrams if you create new ones using the menu in the top-left corner. You can then easily switch between them:

![image](https://user-images.githubusercontent.com/98962/151673170-3c0c6ea8-03a2-49c2-82df-bfe01764e383.png)

You can also bookmark the web address when you are working on a specific diagram and open that link to go back to the specific diagram you were editing.
