### ISSUE TITLE
"Ctrl/Shift and click to add item into selection" functionality

### ISSUE THREAD

**Issue by tst5381** [neo4j-labs/arrows.app#6]
Like what you can do with almost any software.

**Comment by apcj** [comment]
Hi @tst5381 . Thanks for reporting! You should be able to add to (or remove from) selection by clicking with Ctrl (on Windows and Linux) or Cmd (on Mac). However, I suspect we broke something a little while ago for non-Mac users. What Browser and Operating System are you using?

**Comment by tst5381** [comment]
I tried Google Chrome on Windows 7 and Microsoft Edge on Windows 10. In both cases it is the same.

**Comment by apcj** [comment]
Thanks for the info @tst5381 . Keyboard shortcuts should now be fixed on Windows. Please make sure you hard-refresh or clear your cache to get the latest code.
