### ISSUE TITLE
open source code and license

### ISSUE THREAD

**Issue by robinsonkwame** [neo4j-labs/arrows.app#79]
This product has not been updated in several years and appears to be abandoned by Neo4j. Please consider open sourcing the code with an MIT license and let the community work through the issues list.

**Comment by qbeukes** [comment]
Yes please. Where's the code?

**Comment by akollegger** [comment]
> Also it'd be nice to host this locally when running in an isolated network environment.

@PeteDaGuru Would you prefer self-hosting arrows.app or would you be happy with arrows.app being bundled up in something like Neo4j Desktop?

-ABK

**Comment by akollegger** [comment]
> 



> This product has not been updated in several years and appears to be abandoned by Neo4j. Please consider open sourcing the code with an MIT license and let the community work through the issues list.

We are considering making the codebase available as part of a project re-organization. Stay tuned!

-ABK

**Comment by akollegger** [comment]
Code from private repository has been migrated to here, now available under Apache2.

Neo4j Labs will continue to maintain and improve this project. The primary goal is delivering a great application for drawing graphs. A secondary goal is extracting useful libraries from the main codebase.
